using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using GameStart.UI;

namespace GameStart.EditorTools
{
    /// <summary>
    /// Builds a labelled showcase room containing one of every prefab in the project.
    ///
    /// Generated by a menu item rather than committed as a scene asset: scenes are the
    /// worst thing in this repo to hand around (see the binary-serialization issue), and a
    /// room that is entirely derived from the prefab folders would go stale the moment
    /// someone adds a prefab. Re-run the menu item instead and it picks up whatever exists.
    /// </summary>
    public static class DemoRoomBuilder
    {
        private const string ScenePath = "Assets/Scenes/DemoRoom.unity";
        private const string KitFolder = "Assets/Prefabs/Dungeons/SunkenRuins";
        private const string SkyMaterialPath = "Assets/AllSkyFree/Cartoon Base BlueSky/Day_BlueSky_Nothing.mat";

        // The kit is authored around 2-unit floor tiles and 3-unit walls.
        private const float TileSize = 2f;
        private const float WallHeight = 3f;

        // Rooms in the dungeon kit are small; this is deliberately a hall.
        private const int RoomTilesX = 16;
        private const int RoomTilesZ = 16;

        private const float ExhibitSpacing = 5f;
        private const int ExhibitsPerRow = 5;

        /// <summary>Gap between the top of an exhibit and the bottom of its name plate.</summary>
        private const float LabelClearance = 0.5f;

        /// <summary>Gameplay scripts that would otherwise make the exhibits attack or wander.</summary>
        private static readonly string[] BehavioursToDisable =
        {
            "Monster", "MonsterSenses", "MonsterAttack", "MonsterSpawner", "ApexBoss",
        };

        [MenuItem("GameStart/Build Demo Room")]
        public static void BuildFromMenu()
        {
            if (!EditorUtility.DisplayDialog("Build Demo Room",
                    $"This creates (and overwrites) {ScenePath} with one of every prefab, labelled.\n\nContinue?",
                    "Build", "Cancel"))
            {
                return;
            }

            int count = Build();
            EditorUtility.DisplayDialog("Demo Room", $"Built {count} labelled exhibits.\n\nSaved to {ScenePath}.", "OK");
        }

        /// <summary>
        /// Builds and saves the room, returning how many exhibits it placed. No dialogs, so
        /// it can be driven from a script or a build step as well as from the menu.
        /// </summary>
        public static int Build()
        {
            // Additive, and closed again once saved: whatever the author already had open
            // stays open, and unsaved work in it is never at risk. Building Single would
            // quietly take the current scene away from them.
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Additive);
            UnityEngine.SceneManagement.SceneManager.SetActiveScene(scene);

            BuildLighting();
            BuildFloor();
            BuildWalls();
            BuildPillars();

            int placed = BuildExhibits();
            PlacePlayer();

            Directory.CreateDirectory(Path.GetDirectoryName(ScenePath));
            EditorSceneManager.SaveScene(scene, ScenePath);
            EditorSceneManager.CloseScene(scene, true);
            AssetDatabase.Refresh();

            Debug.Log($"Demo room built at {ScenePath}: {RoomTilesX}x{RoomTilesZ} tiles, {placed} labelled exhibits.");
            return placed;
        }

        // ------------------------------------------------------------------ room shell

        private static void BuildLighting()
        {
            var go = new GameObject("Directional Light");
            var light = go.AddComponent<Light>();
            light.type = LightType.Directional;
            light.intensity = 1.1f;
            light.shadows = LightShadows.Soft;
            go.transform.rotation = Quaternion.Euler(50f, -30f, 0f);

            var sky = AssetDatabase.LoadAssetAtPath<Material>(SkyMaterialPath);
            if (sky != null)
            {
                // Light the room from the sky. Ambient has to follow the skybox or the
                // room keeps the flat grey fill and the sky is just a painted backdrop.
                RenderSettings.skybox = sky;
                RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Skybox;
                RenderSettings.ambientIntensity = 1f;
                RenderSettings.defaultReflectionMode = UnityEngine.Rendering.DefaultReflectionMode.Skybox;
                DynamicGI.UpdateEnvironment();
            }
            else
            {
                // No sky asset available: a flat fill still reads better than pitch black.
                RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
                RenderSettings.ambientLight = new Color(0.32f, 0.35f, 0.42f);
            }
        }

        private static void BuildFloor()
        {
            GameObject tile = LoadKit("Kit_FloorTile");
            if (tile == null)
            {
                return;
            }

            var root = new GameObject("Floor").transform;
            for (int x = 0; x < RoomTilesX; x++)
            {
                for (int z = 0; z < RoomTilesZ; z++)
                {
                    var instance = (GameObject)PrefabUtility.InstantiatePrefab(tile, root);
                    instance.transform.position = TilePosition(x, z);
                }
            }
        }

        private static void BuildWalls()
        {
            GameObject wall = LoadKit("Kit_WallSegment");
            if (wall == null)
            {
                return;
            }

            var root = new GameObject("Walls").transform;
            float halfW = RoomTilesX * TileSize * 0.5f;
            float halfD = RoomTilesZ * TileSize * 0.5f;
            float y = WallHeight * 0.5f;

            for (int x = 0; x < RoomTilesX; x++)
            {
                float px = -halfW + TileSize * (x + 0.5f);
                PlaceWall(wall, root, new Vector3(px, y, halfD), 0f);
                PlaceWall(wall, root, new Vector3(px, y, -halfD), 0f);
            }

            for (int z = 0; z < RoomTilesZ; z++)
            {
                float pz = -halfD + TileSize * (z + 0.5f);
                PlaceWall(wall, root, new Vector3(halfW, y, pz), 90f);
                PlaceWall(wall, root, new Vector3(-halfW, y, pz), 90f);
            }
        }

        private static void PlaceWall(GameObject prefab, Transform parent, Vector3 position, float yaw)
        {
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent);
            instance.transform.SetPositionAndRotation(position, Quaternion.Euler(0f, yaw, 0f));
        }

        private static void BuildPillars()
        {
            GameObject pillar = LoadKit("Kit_Pillar");
            if (pillar == null)
            {
                return;
            }

            var root = new GameObject("Pillars").transform;

            // Every fourth tile, inset from the wall so they frame the hall rather than
            // blocking the exhibits laid out down the middle.
            for (int x = 2; x < RoomTilesX - 1; x += 5)
            {
                for (int z = 2; z < RoomTilesZ - 1; z += 5)
                {
                    Vector3 p = TilePosition(x, z);
                    var instance = (GameObject)PrefabUtility.InstantiatePrefab(pillar, root);
                    instance.transform.position = new Vector3(p.x, 1.6f, p.z);
                }
            }
        }

        private static Vector3 TilePosition(int x, int z)
        {
            float halfW = RoomTilesX * TileSize * 0.5f;
            float halfD = RoomTilesZ * TileSize * 0.5f;
            return new Vector3(
                -halfW + TileSize * (x + 0.5f),
                0f,
                -halfD + TileSize * (z + 0.5f));
        }

        // ------------------------------------------------------------------ exhibits

        private static int BuildExhibits()
        {
            var root = new GameObject("Exhibits").transform;
            List<GameObject> prefabs = CollectExhibitPrefabs();

            float rowWidth = (ExhibitsPerRow - 1) * ExhibitSpacing;
            int placed = 0;

            for (int i = 0; i < prefabs.Count; i++)
            {
                int row = i / ExhibitsPerRow;
                int col = i % ExhibitsPerRow;

                var position = new Vector3(
                    -rowWidth * 0.5f + col * ExhibitSpacing,
                    0f,
                    -RoomTilesZ * TileSize * 0.5f + 6f + row * ExhibitSpacing);

                var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefabs[i], root);
                instance.transform.position = position;

                DisableGameplayBehaviours(instance);
                AddLabel(instance, Prettify(prefabs[i].name));
                placed++;
            }

            return placed;
        }

        /// <summary>Every prefab except the player and the kit pieces the room is made of.</summary>
        private static List<GameObject> CollectExhibitPrefabs()
        {
            var results = new List<GameObject>();

            foreach (string guid in AssetDatabase.FindAssets("t:Prefab", new[] { "Assets/Prefabs" }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (path.StartsWith(KitFolder) || path.EndsWith("/Player.prefab"))
                {
                    continue;
                }

                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (prefab != null)
                {
                    results.Add(prefab);
                }
            }

            results.Sort((a, b) => string.CompareOrdinal(a.name, b.name));
            return results;
        }

        private static void DisableGameplayBehaviours(GameObject instance)
        {
            foreach (var behaviour in instance.GetComponentsInChildren<MonoBehaviour>(true))
            {
                if (behaviour == null)
                {
                    continue;
                }

                string type = behaviour.GetType().Name;
                foreach (string name in BehavioursToDisable)
                {
                    if (type == name)
                    {
                        // Exhibits should stand still and be looked at, not hunt the viewer.
                        behaviour.enabled = false;
                        break;
                    }
                }
            }
        }

        private static void AddLabel(GameObject exhibit, string text)
        {
            var go = new GameObject("Label", typeof(TextMesh), typeof(DemoLabel));
            go.transform.SetParent(exhibit.transform, false);

            // Positioned and sized in world terms, not the exhibit's. Prefab roots carry
            // their own scale, so a local offset shrinks with the model - which sank the
            // plates into the taller exhibits - and an inherited scale would make the text
            // a different size on every stand.
            Vector3 top = ExhibitTop(exhibit);
            go.transform.position = new Vector3(top.x, top.y + LabelClearance, top.z);

            Vector3 parentScale = exhibit.transform.lossyScale;
            go.transform.localScale = new Vector3(
                Mathf.Approximately(parentScale.x, 0f) ? 1f : 1f / parentScale.x,
                Mathf.Approximately(parentScale.y, 0f) ? 1f : 1f / parentScale.y,
                Mathf.Approximately(parentScale.z, 0f) ? 1f : 1f / parentScale.z);

            var mesh = go.GetComponent<TextMesh>();
            mesh.text = text;
            mesh.anchor = TextAnchor.LowerCenter;
            mesh.alignment = TextAlignment.Center;
            mesh.fontSize = 64;
            // Big font scaled down, rather than a small font scaled up: keeps the glyphs
            // crisp instead of blocky when the viewer walks right up to a plate.
            mesh.characterSize = 0.06f;
            mesh.color = new Color(1f, 0.96f, 0.88f, 1f);

            go.GetComponent<DemoLabel>().SetText(text);
        }

        /// <summary>World point at the centre-top of everything the exhibit renders.</summary>
        private static Vector3 ExhibitTop(GameObject exhibit)
        {
            Bounds bounds = default;
            bool has = false;

            foreach (var renderer in exhibit.GetComponentsInChildren<Renderer>(true))
            {
                if (!has)
                {
                    bounds = renderer.bounds;
                    has = true;
                }
                else
                {
                    bounds.Encapsulate(renderer.bounds);
                }
            }

            if (!has)
            {
                return exhibit.transform.position + Vector3.up * 2.2f;
            }

            return new Vector3(bounds.center.x, bounds.max.y, bounds.center.z);
        }

        private static void PlacePlayer()
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Player/Player.prefab");
            if (prefab == null)
            {
                Debug.LogWarning("DemoRoomBuilder: Player.prefab not found; the room has no spawn.");
                return;
            }

            var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
            instance.transform.position = new Vector3(0f, 0.1f, -RoomTilesZ * TileSize * 0.5f + 2f);
        }

        // ------------------------------------------------------------------ helpers

        private static GameObject LoadKit(string name)
        {
            string path = $"{KitFolder}/{name}.prefab";
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (prefab == null)
            {
                Debug.LogWarning($"DemoRoomBuilder: missing kit piece {path}; that part of the room is skipped.");
            }

            return prefab;
        }

        /// <summary>"Monster_Ranged_Houndling" -> "Monster Ranged Houndling".</summary>
        private static string Prettify(string name)
        {
            return name.Replace('_', ' ');
        }
    }
}
